version: '3'
services:

  uwsgi:
    build: ./app
    volumes:
      - ./logs/uwsgi/:/var/log/uwsgi/
      - ./app:/usr/src/app/
    env_file: ./app/.env
    ports:
      - "3031:3031"
    environment:
      - "TZ=Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      - "TZ=Asia/Tokyo"
